#!/usr/bin/env bash
# Script that install nginx on your web-01 server
# Configure my Nginx server so that /redirect_me is redirecting to another page.
# The redirection used is “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
# Create a custom index.html file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

file="/etc/nginx/sites-available/default"
new_string="location /redirect_me {"
location="return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;"
sudo sed -i "s#location / {#${new_string}#" $file
sudo sed -i "s#try_files \$uri \$uri/ =404;#${location}#" $file
sudo service nginx restart
