#!/usr/bin/env bash
# Configure my Nginx server to have a custom 404 page
# that contains the string: "Ceci n'est pas une page".

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
error_page="/var/www/html/custom_404.html"
echo "Ceci n'est pas une page" | sudo tee $error_page
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        
        error_page 404 /custom_404.html;
        location = /custom_404.html {
                internal;
        }

}" > default

sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
