#!/usr/bin/env bash
# Using what I did for task #1, make my fix short and sweet.
chmod u+rw /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill apache2
sudo service nginx start
